### ISSUE TITLE
Permission issue adding lines to easy-install.pth with anaconda3

### ISSUE THREAD

**Issue by fungs** [fungs/mglex#1]
More details are needed.

**Comment by dspeth** [comment]
I doubt this needs to be an outstanding issue. My initial installation of the package could not be completed due to a lack of permission to write in ../anaconda3/lib/python3.5/site-packages/easy-install.pth 

As far as I can tell, only the path to MGLEX dependency docopt is added to easy-install.pth  A colleague had installed anaconda3 and apparently write permissions for ../anaconda3/lib/python3.5/site-packages/easy-install.pth default to user only.

**Comment by fungs** [comment]
Restricting write access to the user running Anaconda seems reasonable from a security point of view. As I understand your comment, this was causing the error. Unfortunately I cannot reproduce and I don't know how Anaconda is set up on Mac, because I don't have one. Multi-user setup for Anaconda works, however, on Linux, if it is properly configured.

Otherwise, there are permission problems documented with Anaconda and Mac:
https://docs.continuum.io/anaconda/faq#id21

The MGLEX installation using Anaconda environments as a user on Linux systems seems to work just fine both for Python 3.5 and 3.6.

**Comment by fungs** [comment]
I'm closing this for now, as it seemed to be an isolated issue.
